### ISSUE TITLE
Hugo's "googleAnalytics" vs Pickles's "ga_api_key"

### ISSUE THREAD

**Issue by whhone** [mismith0227/hugo_theme_pickles#129]
From the [Hugo's documentation](https://gohugo.io/getting-started/configuration/#all-configuration-settings), there is a `googleAnalytics` config. 
From this theme, there is a `ga_api_key` config.

Are they the same thing? If they are, should the pickles theme uses the official one?

**Comment by dwmkerr** [comment]
Agreed, it seems that it would be sensible to use the standard one from the basic Hugo config.

**Comment by d-kusk** [comment]
I think it's better to use Hugo settings.
https://gohugo.io/templates/internal/#google-analytics
