### ISSUE TITLE
The color of hyperlink is not distinguishable from normal text

### ISSUE THREAD

**Issue by whhone** [mismith0227/hugo_theme_pickles#130]
I am on the release branch https://github.com/mismith0227/hugo_theme_pickles/commit/4a8b235cd827dbada5b490c66e999e8bba7761b6.

Expected: The generated HTML should differentiate normal text and hyper link.

Actual: Normal text and hyper link are not distinguishable. Hyper links are not underscored and they have the same color as normal text.

**Comment by dwmkerr** [comment]
I *think* PR #131 fixes this but am not very familiar with SCSS!
