### ISSUE TITLE
Can't run dev server with provided instructions

### ISSUE THREAD

**Issue by annabunches** [mismith0227/hugo_theme_pickles#147]
Tried to spin up the dev server. `yarn` and `yarn run dev` work fine, but if run from the root directory, `hugo server` fails with:

```
Error: Unable to locate config file or config directory. Perhaps you need to create a new site.
       Run `hugo help new` for details.
```

which makes sense, since there isn't actually a hugo site there. However, running `hugo server` from `exampleSite` also fails with:

```
Error: Error building site: "/home/anna/code/hugo_theme_pickles/exampleSite/content/posts/image-zoom-sample.md:13:1": failed to extract shortcode: template for shortcode "zoom-img" not found  
```

it seems to me that either I'm missing an undeclared dependency, or the example site can't actually see/use the theme correctly out of the box.

Environment notes:
* Ubuntu 20.04
* yarn 1.22.4
* nodejs 10.19.0
* hugo 0.70.0

**Comment by dwmkerr** [comment]
I have submitted PR #172 which resolves this issue. For now, as a workaround, I would suggest that you run the following command from the project root directory:

```
hugo server -s exampleSite --baseUrl http://localhost --themesDir=../../ --theme=hugo_theme_pickles
```
