### ISSUE TITLE
/posts page

### ISSUE THREAD

**Issue by bbohling** [mismith0227/hugo_theme_pickles#17]
Displays ALL posts yet still has pagination at the bottom of the page.

**Comment by mismith0227** [comment]
Hi @bbohling 

I am sorry that I am not good at English.
Is this about that?

<img width="371" alt="2017-08-27 21 38 56" src="https://user-images.githubusercontent.com/11687509/29749856-4fb29b8c-8b70-11e7-8279-e04a6c453944.png">

Is it better to hide when there is only one page?

**Comment by stilesb** [comment]
Still an issue - paging does not work correctly for /posts

**Comment by lukehsiao** [comment]
Paging is working correctly for me in `/posts`. Did you set the `paginate` parameter in your config.toml?

```toml
paginate = 10  # The number of posts per page
```

You may want to try a smaller number and see if the pagination kicks in.

**Comment by bbohling** [comment]
Yes, I have tried `paginate` and it does not honor that number on the `/posts` page, but it does on the homepage.

**Comment by stilesb** [comment]
So, the index page pagination works. Posts does not. I'll open a PR with my patch, but gist is in the `list.html` layout. It should be:

```
{{ partial "header.html" . }}
<h2 class="c-title tag-title">{{ .Title }}</h2>
{{ range $index, $page := (.Paginate (where .Data.Pages "Type" "posts")).Pages }}
{{ if ne $index 0 }}
{{ end }}
{{ .Render "li" }}
{{ end }}
{{ partial "pagination.html" .Paginator }}
{{ partial "siteinfo.html" . }}
{{ partial "footer.html" . }}
```

**Comment by stilesb** [comment]
However, I believe this will only paginate from the `posts` directory... any idea how to generalize this?

**Comment by bbohling** [comment]
I haven't tried myself, but possibly [looking](https://github.com/laozhu/hugo-nuo/blob/master/layouts/_default/links.html) at [another](https://github.com/alanorth/hugo-theme-bootstrap4-blog/blob/master/layouts/_default/list.html) [theme's](https://github.com/nodejh/hugo-theme-cactus-plus/blob/master/layouts/_default/list.html) [implementation](https://github.com/jbub/ghostwriter/blob/master/layouts/_default/list.html) would help.

**Comment by stilesb** [comment]
https://github.com/mismith0227/hugo_theme_pickles/pull/20

**Comment by lukehsiao** [comment]
Ah, I didn't realize you were talking about pagination for _not_ the index page, I was just looking at the homepage.

**Comment by mismith0227** [comment]
@bbohling @lukehsiao @stilesb 
Thank you! Thank you for pull request as well.
I will check it, please wait.
