### ISSUE TITLE
Tagのリンクが不正(？)

### ISSUE THREAD

**Issue by serinuntius** [mismith0227/hugo_theme_pickles#18]
キレイなテーマの提供ありがとうございます。
とても感謝しております。

https://github.com/mismith0227/hugo_theme_pickles/blob/9f140709d1d51cf3b5a0af5b19ece868a94bdfa5/layouts/_default/single.html#L14

該当行なのですが、baseurlの最後の `/` と `/tags/` の先頭の `/` が被ってしまい
`example.com//tags/~~`  のようなリンクになってしまい、404になってしまいます。

baseurlを `https://example.com` 等にし、 `/` を無くせばいいかと思ったのですが、
そうするとtwitter等のsvgが表示されなくなってしまいました。

```html
      <a href="{{ $baseurl }}tags/{{ . | urlize }}" class="c-tag">{{ . }}</a>
```

`/` をなくすのが一番手っ取り早そうなので、そのように対応しました。

**Comment by serinuntius** [comment]
ちなみに、Hugoの仕組みに詳しくないので、原因はわかっておりませんが、
該当バグはビルドしたときだけ起こるような気がします。

`hugo server` では、きちんとしたリンクが表示されます。
localhost:1313のbaseurl は 後ろに `/` がついてないのかな・・・

よくわかってないです。

**Comment by mismith0227** [comment]
@serinuntius 使って頂いてありがとうございます！また、プルリクもありがとうございます！
プルリク確認して問題なさそうだったら、マージします。報告ありがとうございました。

**Comment by mismith0227** [comment]
@serinuntius マージしました！確かに`/`が重複してました。。
細かいところ気づいていただいてありがとうございます。
