### ISSUE TITLE
Tags list items appends "1"

### ISSUE THREAD

**Issue by yangmillstheory** [mismith0227/hugo_theme_pickles#23]
Front matter:

```
---
title: "Hello, world!"
date: 2017-09-01T10:17:15-07:00
draft: false
description: "My first post."
tags:
  - "foo"
  - "bar"
---

...
```

![image](https://user-images.githubusercontent.com/2729079/29992324-15f9d284-8f4e-11e7-9a81-4cc09f886bc8.png)

Related question, is there any way to expose links to `/tags` and `/categories` from the theme?

**Comment by yangmillstheory** [comment]
Oh sorry, I see that that's the number of posts for that category. Can we use something like (1) instead?

Thanks for your work here by the way, I love this theme.

**Comment by mismith0227** [comment]
Hi @yangmillstheory 
Thank you pull request! Merged.

> Related question, is there any way to expose links to /tags and /categories from the theme?

I'm sorry, but now there is no way. I will think about something.

**Comment by mismith0227** [comment]
Hi @yangmillstheory 

> Related question, is there any way to expose links to /tags and /categories from the theme?

It can be set with [config.toml](https://github.com/mismith0227/hugo_theme_pickles/blob/master/exampleSite/config.toml).

Please see exampleSite for details

https://github.com/mismith0227/hugo_theme_pickles/tree/master/exampleSite
