### ISSUE TITLE
GitLab account support

### ISSUE THREAD

**Issue by manheraz** [mismith0227/hugo_theme_pickles#33]
Hi!

Thank you for this theme! Is really nice...

Any chance to add GitLab to the supported social accounts list?

Here is one of the official SVG images in grayscale: [stacked_wm_grayscale.svg](https://gitlab.com/gitlab-com/gitlab-artwork/raw/master/wordmark/stacked_wm_grayscale.svg)

Thanks in advance.

**Comment by mismith0227** [comment]
Hi! @manheraz 

Thank you!

I will add GitLab. Please wait several days.

**Comment by manheraz** [comment]
Thank you, @mismith0227 !

Don't worry, there's no hurry.

Very appreciated...!

**Comment by mismith0227** [comment]
@manheraz 

I added the icon of GitLab.

```
# config.toml
[params]
  gitlab = "Your GitLab username"
```

<img width="232" alt="2017-10-23 22 30 45" src="https://user-images.githubusercontent.com/11687509/31892528-388087c0-b844-11e7-9bbc-ac10aedcb62a.png">

**Comment by manheraz** [comment]
That was incredibly fast!

Thank you!
