### ISSUE TITLE
/tags/* is broken?

### ISSUE THREAD

**Issue by yangmillstheory** [mismith0227/hugo_theme_pickles#37]
See https://blog.yangmillstheory.com/tags/, and try to click "vim".

Am I missing something in `config.toml`?

**Comment by mismith0227** [comment]
Hi @yangmillstheory !

Perhaps it may be config.toml's baseurl `/`
Is there a `/` at the end?

```
baseurl = "https://blog.yangmillstheory.com/"
```

**Comment by yangmillstheory** [comment]
Yes, is that correct?```baseurl = "https://blog.yangmillstheory.com/"languageCode = "en-us"Title = "@yangmillstheory"# Copyright notice. This is displayer in the footer.copyright = "&copy; Copyright notice"PygmentsCodeFences = truepygmentsstyle = "friendly"[params]  paginate = 10  # Social accounts. Link to these accounts are displayed in the header and  # footer  twitter = "yangmillstheory"  # facebook = "Your Facebook username"  # instagram = "Your Instagram username"  # googleplus = "Your Google+ user id"  github = "yangmillstheory"  npm = "yangmillstheory"  # codepen = "Your CodePen username"  # dribbble = "Your Dribbble username"  # fivehundredpx = "Your 500px username" # 500px  # flickr = "Your Flickr username"  # pinterest = "Your Pinterest username"  # tumblr = "Your Tumblr username"  # vimeo = "Your Vimeo username"  # youtube = ""  linkedin = "yangmillstheory"  # Disqus shortname  # disqus = ""  # Google Analytics API key.  ga_api_key = ""  author = "Victor Alvarez"  authorwebsite = "https://blog.yangmillstheory.com"  avatar = "https://secure.gravatar.com/avatar/b96492deee09a651867f0ec4efbf48aa"  contact = "mailto:v.alvarez312@gmail.com"  bio = "Mathematician turned software engineer living in sunny California."  # Short subtitle/tagline. This is displayed in the header.  subtitle = "code, climbing, and everything else"  # Logo image. This is displayed ogp image.  logo = ""  favicon = "favicon.ico"[[menu.main]]  name = "Blog"  url = "/"  weight = 1[[menu.main]]  name = "Categories"  url = "/categories"  weight = 2[[menu.main]]    name = "Tags"    url = "/tags"    weight = 3[[menu.main]]  name = "About"  url = "/about"  weight = 4```
          
            
            On Dec 8 2017, at 2:49 pm, misumi <notifications@github.com> wrote:
            
            
              Hi @yangmillstheory !
Perhaps it may be config.toml's baseurl /
Is there a / at the end?
baseurl = "https://blog.yangmillstheory.com/"

**Comment by yangmillstheory** [comment]
That fixed the issue (strip leading `/`, and change to `https://blog.yangmillstheory.com`), but I had to change:

* https://github.com/mismith0227/hugo_theme_pickles/blob/master/layouts/partials/head.html#L49
* https://github.com/mismith0227/hugo_theme_pickles/blob/master/layouts/partials/head.html#L42

Thanks @mismith0227 ❤️
