### ISSUE TITLE
Hide date in certain pages

### ISSUE THREAD

**Issue by dartzon** [mismith0227/hugo_theme_pickles#71]
Is it possible to hide the publishing date in certain pages like **about** for example?

**Comment by juriansluiman** [comment]
I had the same issue, this is located in the `single.html` file. You can override this by creating a new file `layouts/_default/single.html`.

You can hide dates in non-posts by using this conditional:

    {{ if eq .Type "posts" }}
        // html
    {{ end }}

So I replaced this:

      <div class="c-time">
        Posted on
        <time datetime="{{ .Date.Format "2006-01-02T15:04:05Z07:00" | safeHTML }}">
          {{ .Date.Format "Jan 2, 2006" }}
        </time>
      </div>

By this:

      {{ if eq .Type "article" }}
      <div class="c-time">
        Posted on
        <time datetime="{{ .Date.Format "2006-01-02T15:04:05Z07:00" | safeHTML }}">
          {{ .Date.Format "Jan 2, 2006" }}
        </time>
      </div>
      {{ end }}

I did the same with the Older/Newer, but you get the gist by this example.

**Comment by ckoehler** [comment]
I'd like the same thing. I can make the modification, but I'd prefer a built-in solution.

**Comment by charleslaw** [comment]
Is this related to #100 ?

**Comment by juriansluiman** [comment]
@charleslaw no, #100 is because of this line:
https://github.com/mismith0227/hugo_theme_pickles/blob/d12aafb104cca1cc4614875842968ea1c59f5173/layouts/_default/list.html#L5

**Comment by charleslaw** [comment]
I'm am new to hugo, so please take this with a grain of salt.

An about page seems like it should not have tags (or tags are ignored), not be connected to other posts via older/newer (it neither includes the links & other posts don't reference it), and it does not include a date.

Your solution seems very nice, but I wonder (haven't tested) if someone is using older/newer to go through posts would a post link to the about page?

Also, what would a built-in solution look like?

**Comment by dwmkerr** [comment]
A built in, or at least idomatic solution for the theme would be to use the front matter:

For example, on this page, https://dwmkerr.com/page/speaking/ would do this:

```
---
author: Dave Kerr
date: "2014-05-03T14:59:27Z"
description: ""
draft: false
slug: about
title: About
hideDate: true
---
```

**Comment by dwmkerr** [comment]
I've added PR #158 which I believe solves this issue. Of course it adds complexity so @mismith0227 may prefer to let people to simple leave this as something they handle themselves with their own partials!

**Comment by mismith0227** [comment]
@dwmkerr Sorry for being late!
I was really into Animal Crossing.

Thank you for PR!

**Comment by dwmkerr** [comment]
Lol no worries! Have fun :)
